<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>catch方法</title>
</head>
<body>
    <script>
        const p = new Promise((resolve, reject) => {
           setTimeout(()=>{
               // 设置p对象的状态为失败，并设置失败的值
               reject("出错啦！！！");
           }, 1000);
        });

        /*p.then(value=>{}, reason =>{
            console.error(reason);
        })*/

        p.catch(reason => {
            console.warn(reason);
        });
    </script>
</body>
</html>